name: Update mapper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download latest mapper file
        run: |
          mkdir ${{ runner.temp }}/json
          curl https://github.com/Fribb/anime-lists/blob/master/anime-list-mini.json -o ${{ runner.temp }}/json/anime-list-mini.json

      - name: Edit mapper json file
        uses: actions/github-script@v7
        env:
          INPUT_FILE: ${{ runner.temp }}/json/anime-list-mini.json
          OUTPUT_FILE: ./anime-list-mini.json
        with:
          script: |
            const { INPUT_FILE, OUTPUT_FILE } = process.env
            const fs = require('fs')
            let input = require(INPUT_FILE)
            let stringified = JSON.stringify(input, ["mal_id", "kitsu_id"]) 
            fs.writeFileSync(OUTPUT_FILE, stringified) 

      - name: Create pull request
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updating mapper json file
